<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="943" started-at="2019-03-31T07:36:53Z" finished-at="2019-03-31T07:36:54Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="943" started-at="2019-03-31T07:36:53Z" finished-at="2019-03-31T07:36:54Z">
      <class name="PNC.baseTest">
        <test-method status="FAIL" signature="sample(java.lang.String)[pri:0, instance:PNC.baseTest@c4039c]" name="sample" duration-ms="0" started-at="2019-03-31T07:36:54Z" data-provider="retrivedata" finished-at="2019-03-31T07:36:54Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.util.ArrayList PNC.baseTest.retrivedata() throws java.io.IOException must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not class java.util.ArrayList]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.ArrayList PNC.baseTest.retrivedata() throws java.io.IOException must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not class java.util.ArrayList
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:156)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sample -->
      </class> <!-- PNC.baseTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
